AppBundle\Entity\Producer:
    type: entity
    table: producer
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            column: name
            type: string
            length: 45